version: "3"

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=password
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  votewatch-volume:
    external: true
